# Generated by Django 5.2.4 on 2025-08-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_flower_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
